Lab_02/Bai_3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai_3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Lab_02/Bai_3/Controllers/MusicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bai_3.Controllers
{
    public class MusicController : Controller
    {
        // GET: Music
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listen(String musicName)
        {
            ViewBag.MusicName = musicName;
            return View();
        }
        public ActionResult Download(string musicName)
        {
            var filePath = Server.MapPath("~/Content/music/" + musicName + ".mp3");

            if (System.IO.File.Exists(filePath))
            {
                return File(filePath, "audio/mpeg", musicName + ".mp3");
            }
            else
            {
                return HttpNotFound();
            }
        }

    }
}

Lab_02/Bai_3/Views/Music/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BẢNG XẾP HẠNG THÁNG 12</h2>

<ol>
    <li>
        @Html.ActionLink("Sao Trời Làm Gió", "Listen", new
   {
            MusicName = "SaoTroiLamGio"
        })
        <span class="ms-lg-4">
            @Html.ActionLink("Tải xuống", "Download", new
       {
           MusicName = "SaoTroiLamGio"
       })
        </span>
    </li>
    <li>
        @Html.ActionLink("Sầu Tím Thiệp Hồng", "Listen", new
   {
       MusicName = "SauTimThiepHong"
   })
        <span class="ms-lg-4">
            @Html.ActionLink("Tải xuống", "Download", new
       {
           MusicName = "SauTimThiepHong"
       })
        </span>
    </li>
    <li>
        @Html.ActionLink("Từng Quen", "Listen", new
   {
       MusicName = "TungQuen"
   })
        <span class="ms-lg-4">
            @Html.ActionLink("Tải xuống", "Download", new
       {
           MusicName = "TungQuen"
       })
        </span>
    </li>
    <li>
        @Html.ActionLink("Nối Lại Tình Xưa", "Listen", new
   {
       MusicName = "NoiLaiTinhXua"
   })
        <span class="ms-lg-4">
            @Html.ActionLink("Tải xuống", "Download", new
       {
           MusicName = "NoiLaiTinhXua"
       })
        </span>
    </li>
</ol>

Lab_02/Bai_3/Views/Music/Listen.cshtml
@{
    ViewBag.Title = "Listen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.MusicName</h2>

<audio controls>
    <source src="~/Content/music/@{@ViewBag.MusicName}.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>

Lab_02/Bai_3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Nhạc Việt Nam", "Index", "Music", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>